/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./dist/index.html"],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#b7b8c2",
        "inverse-primary": "#00696e",
        "on-secondary": "#2e3039",
        "secondary-container": "#474952",
        "on-secondary-fixed": "#191b23",
        "error": "#ffb4ab",
        "on-surface-variant": "#b9caca",
        "surface-container-high": "#282a2e",
        "tertiary-fixed-dim": "#ffb59c",
        "surface": "#111317",
        "surface-container-low": "#1a1c20",
        "background": "#111317",
        "on-primary-fixed": "#002021",
        "tertiary-container": "#ffd4c7",
        "primary-fixed": "#63f7ff",
        "surface-dim": "#111317",
        "on-secondary-fixed-variant": "#45464f",
        "outline-variant": "#3a494a",
        "primary": "#e9feff",
        "on-tertiary-container": "#b03700",
        "on-tertiary": "#5c1900",
        "on-primary-container": "#006c71",
        "surface-tint": "#00dce5",
        "on-primary": "#003739",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#832700",
        "on-error-container": "#ffdad6",
        "primary-container": "#00f5ff",
        "on-tertiary-fixed": "#390c00",
        "tertiary": "#fff8f7",
        "surface-container-lowest": "#0c0e12",
        "surface-container-highest": "#333539",
        "on-primary-fixed-variant": "#004f53",
        "secondary-fixed-dim": "#c5c6d1",
        "surface-bright": "#37393e",
        "tertiary-fixed": "#ffdbcf",
        "on-background": "#e2e2e8",
        "surface-container": "#1e2024",
        "outline": "#849495",
        "on-surface": "#e2e2e8",
        "error-container": "#93000a",
        "secondary": "#c5c6d1",
        "primary-fixed-dim": "#00dce5",
        "inverse-on-surface": "#2f3035",
        "secondary-fixed": "#e1e1ed",
        "surface-variant": "#333539",
        "inverse-surface": "#e2e2e8",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-page": "24px",
        "panel-width": "280px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-xs": "4px",
        gutter: "12px",
      },
      fontFamily: {
        "data-lg": ["JetBrains Mono"],
        "headline-md": ["Inter"],
        "data-mono": ["JetBrains Mono"],
        "title-sm": ["Inter"],
        "label-xs": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "display-lg": ["Inter"],
      },
      fontSize: {
        "data-lg": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "data-mono": [
          "13px",
          { lineHeight: "16px", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        "title-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "label-xs": ["11px", { lineHeight: "14px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};
